image: node:12

definitions:
    - step: &AWS-S3_Deploy
        name: S3-Prod Deploy
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-1"
              S3_BUCKET: $AWS_S3_BUCKET
              LOCAL_PATH: "."
              ACL: "public-read"
              DELETE_FLAG: "true"
              EXTRA_ARGS: "--follow-symlinks"

pipelines:
  branches:
    master:
      - step: *AWS-S3_Deploy

  custom:
    deploy-to-s3:
      - step:
          <<: *AWS-S3_Deploy
          name: S3-Prod Manual Deploy
